// ─────────────────────────────────────────────────────────────
//  TEAM 4 — Notification Analyst
//  Formats and delivers the daily FX signal report
// ─────────────────────────────────────────────────────────────

import { CONFIG } from "../config/settings.js";
import { log } from "./claude_client.js";
import fs from "fs";
import path from "path";

export async function runNotificationAnalyst(allSignals, allAnalystOutputs, date) {
  log("Notification Analyst", "Composing daily signal report...");

  // ── Build the report ─────────────────────────────────────────
  const activeBuys  = allSignals.filter(s => s.signal.includes("🟢 BUY"));
  const activeSells = allSignals.filter(s => s.signal.includes("🔴 SELL"));
  const holds       = allSignals.filter(s => s.signal.includes("⚪ HOLD"));

  const header = `
# 📊 FX Signal Report — ${date}
*Generated at 08:00 JST by FX Signal Generator*

---

## 🔔 Signal Summary

| Pair | Signal | Confidence |
|------|--------|------------|
${allSignals.map(s => {
  const signalLine = s.signal.match(/\| Signal\s*\|\s*(.*?)\s*\|/)?.[1] || "—";
  const confLine   = s.signal.match(/\| Confidence\s*\|\s*(.*?)\s*\|/)?.[1] || "—";
  return `| ${s.pair} | ${signalLine} | ${confLine} |`;
}).join("\n")}

---

## Active Signals (${activeBuys.length} Buy, ${activeSells.length} Sell)
`;

  const signalDetails = allSignals.map(s => s.signal).join("\n\n---\n\n");

  const footer = `
---
*Report generated by FX Signal Generator | Multi-agent system*
*Pairs analysed: ${allSignals.map(s => s.pair).join(", ")}*
*Not financial advice. Always apply your own risk management.*
`;

  const fullReport = header + "\n" + signalDetails + footer;

  // ── Save to file ─────────────────────────────────────────────
  if (CONFIG.saveReports) {
    const outputDir = CONFIG.outputDir;
    if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

    const filename = `fx-signals-${date.replace(/\//g, "-")}.md`;
    const filepath = path.join(outputDir, filename);
    fs.writeFileSync(filepath, fullReport, "utf8");
    log("Notification Analyst", `Report saved → ${filepath}`);

    // Also save raw JSON for programmatic use
    const jsonPath = path.join(outputDir, `fx-signals-${date.replace(/\//g, "-")}.json`);
    fs.writeFileSync(jsonPath, JSON.stringify({
      date,
      signals: allSignals,
      pairs: allSignals.map(s => s.pair),
      summary: {
        buys: activeBuys.map(s => s.pair),
        sells: activeSells.map(s => s.pair),
        holds: holds.map(s => s.pair),
      }
    }, null, 2), "utf8");
    log("Notification Analyst", `JSON saved → ${jsonPath}`);
  }

  // ── Deliver notification ──────────────────────────────────────
  const method = CONFIG.notification.method;

  if (method === "console" || method === "both") {
    console.log("\n" + "═".repeat(70));
    console.log(fullReport);
    console.log("═".repeat(70) + "\n");
  }

  if (method === "email" || method === "both") {
    await sendEmail(fullReport, date);
  }

  log("Notification Analyst", "✓ Notification delivered");
  return fullReport;
}

async function sendEmail(reportMarkdown, date) {
  try {
    const { default: nodemailer } = await import("nodemailer");
    const { email } = CONFIG.notification;

    const transporter = nodemailer.createTransporter({
      host: email.smtpHost,
      port: email.smtpPort,
      secure: email.smtpPort === 465,
      auth: { user: email.smtpUser, pass: email.smtpPass },
    });

    // Convert markdown to simple HTML
    const htmlBody = reportMarkdown
      .replace(/^#{1,3} (.+)/gm, (_, t) => `<h2>${t}</h2>`)
      .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
      .replace(/\n/g, "<br>")
      .replace(/🟢/g, '<span style="color:green">🟢</span>')
      .replace(/🔴/g, '<span style="color:red">🔴</span>');

    await transporter.sendMail({
      from: email.from,
      to: email.to,
      subject: `📊 FX Signals ${date} — ${CONFIG.pairs.join(", ")}`,
      text: reportMarkdown,
      html: `<pre style="font-family: monospace; font-size: 13px;">${htmlBody}</pre>`,
    });

    log("Notification Analyst", `✉️  Email sent to ${email.to}`);
  } catch (err) {
    log("Notification Analyst", `⚠️  Email failed: ${err.message}`);
    log("Notification Analyst", "Falling back to console output...");
    console.log(reportMarkdown);
  }
}
